# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from . import user_proto_pb2 as user__proto__pb2


class UserServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.register_api = channel.unary_unary(
        '/UserService/register_api',
        request_serializer=user__proto__pb2.RegisterRequest.SerializeToString,
        response_deserializer=user__proto__pb2.RegisterResponse.FromString,
        )
    self.get_user_info_by_uuid = channel.unary_unary(
        '/UserService/get_user_info_by_uuid',
        request_serializer=user__proto__pb2.GetUserInfoRequest.SerializeToString,
        response_deserializer=user__proto__pb2.GetUserInfoResponse.FromString,
        )


class UserServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def register_api(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def get_user_info_by_uuid(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_UserServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'register_api': grpc.unary_unary_rpc_method_handler(
          servicer.register_api,
          request_deserializer=user__proto__pb2.RegisterRequest.FromString,
          response_serializer=user__proto__pb2.RegisterResponse.SerializeToString,
      ),
      'get_user_info_by_uuid': grpc.unary_unary_rpc_method_handler(
          servicer.get_user_info_by_uuid,
          request_deserializer=user__proto__pb2.GetUserInfoRequest.FromString,
          response_serializer=user__proto__pb2.GetUserInfoResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'UserService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
