// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/user_proto.proto

package user_proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RegisterRequest struct {
	FirstName            string   `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	FamilyName           string   `protobuf:"bytes,2,opt,name=family_name,json=familyName,proto3" json:"family_name,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterRequest) Reset()         { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()    {}
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc5045f2523e14cc, []int{0}
}

func (m *RegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest.Unmarshal(m, b)
}
func (m *RegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest.Marshal(b, m, deterministic)
}
func (m *RegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest.Merge(m, src)
}
func (m *RegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest.Size(m)
}
func (m *RegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest proto.InternalMessageInfo

func (m *RegisterRequest) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *RegisterRequest) GetFamilyName() string {
	if m != nil {
		return m.FamilyName
	}
	return ""
}

func (m *RegisterRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type RegisterResponse struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	UserId               int32    `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterResponse) Reset()         { *m = RegisterResponse{} }
func (m *RegisterResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterResponse) ProtoMessage()    {}
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc5045f2523e14cc, []int{1}
}

func (m *RegisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResponse.Unmarshal(m, b)
}
func (m *RegisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResponse.Marshal(b, m, deterministic)
}
func (m *RegisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResponse.Merge(m, src)
}
func (m *RegisterResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterResponse.Size(m)
}
func (m *RegisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResponse proto.InternalMessageInfo

func (m *RegisterResponse) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *RegisterResponse) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *RegisterResponse) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type GetUserInfoRequest struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserInfoRequest) Reset()         { *m = GetUserInfoRequest{} }
func (m *GetUserInfoRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserInfoRequest) ProtoMessage()    {}
func (*GetUserInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc5045f2523e14cc, []int{2}
}

func (m *GetUserInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserInfoRequest.Unmarshal(m, b)
}
func (m *GetUserInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserInfoRequest.Marshal(b, m, deterministic)
}
func (m *GetUserInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserInfoRequest.Merge(m, src)
}
func (m *GetUserInfoRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserInfoRequest.Size(m)
}
func (m *GetUserInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserInfoRequest proto.InternalMessageInfo

func (m *GetUserInfoRequest) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

type GetUserInfoResponse struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	FirstName            string   `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	FamilyName           string   `protobuf:"bytes,3,opt,name=family_name,json=familyName,proto3" json:"family_name,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	UserId               int32    `protobuf:"varint,5,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	EmailIsValid         bool     `protobuf:"varint,6,opt,name=email_is_valid,json=emailIsValid,proto3" json:"email_is_valid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserInfoResponse) Reset()         { *m = GetUserInfoResponse{} }
func (m *GetUserInfoResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserInfoResponse) ProtoMessage()    {}
func (*GetUserInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc5045f2523e14cc, []int{3}
}

func (m *GetUserInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserInfoResponse.Unmarshal(m, b)
}
func (m *GetUserInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserInfoResponse.Marshal(b, m, deterministic)
}
func (m *GetUserInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserInfoResponse.Merge(m, src)
}
func (m *GetUserInfoResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserInfoResponse.Size(m)
}
func (m *GetUserInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserInfoResponse proto.InternalMessageInfo

func (m *GetUserInfoResponse) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *GetUserInfoResponse) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *GetUserInfoResponse) GetFamilyName() string {
	if m != nil {
		return m.FamilyName
	}
	return ""
}

func (m *GetUserInfoResponse) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *GetUserInfoResponse) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *GetUserInfoResponse) GetEmailIsValid() bool {
	if m != nil {
		return m.EmailIsValid
	}
	return false
}

func init() {
	proto.RegisterType((*RegisterRequest)(nil), "user_proto.RegisterRequest")
	proto.RegisterType((*RegisterResponse)(nil), "user_proto.RegisterResponse")
	proto.RegisterType((*GetUserInfoRequest)(nil), "user_proto.GetUserInfoRequest")
	proto.RegisterType((*GetUserInfoResponse)(nil), "user_proto.GetUserInfoResponse")
}

func init() {
	proto.RegisterFile("proto/user_proto.proto", fileDescriptor_bc5045f2523e14cc)
}

var fileDescriptor_bc5045f2523e14cc = []byte{
	// 341 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0x4d, 0x4f, 0xc2, 0x40,
	0x10, 0xb5, 0x7c, 0x29, 0x03, 0x51, 0xb3, 0x7e, 0x11, 0xfc, 0x80, 0x34, 0x26, 0xe2, 0x05, 0x12,
	0xfd, 0x07, 0x5e, 0x0c, 0x31, 0xf1, 0x50, 0x83, 0x07, 0x2e, 0x9b, 0x42, 0xa7, 0x65, 0x0d, 0xdd,
	0xc5, 0xee, 0x96, 0x84, 0x3f, 0xe6, 0xd1, 0xdf, 0x66, 0x3a, 0x85, 0x50, 0x90, 0xea, 0xa5, 0xdd,
	0x79, 0x6f, 0x66, 0xf6, 0xcd, 0x9b, 0x85, 0xf3, 0x59, 0xa4, 0x8c, 0xea, 0xc5, 0x1a, 0x23, 0x4e,
	0xc7, 0x2e, 0x7d, 0x19, 0xac, 0x11, 0x3b, 0x80, 0x23, 0x07, 0x03, 0xa1, 0x0d, 0x46, 0x0e, 0x7e,
	0xc6, 0xa8, 0x0d, 0xbb, 0x06, 0xf0, 0x45, 0xa4, 0x0d, 0x97, 0x6e, 0x88, 0x0d, 0xab, 0x6d, 0x75,
	0xaa, 0x4e, 0x95, 0x90, 0x57, 0x37, 0x44, 0xd6, 0x82, 0x9a, 0xef, 0x86, 0x62, 0xba, 0x48, 0xf9,
	0x02, 0xf1, 0x90, 0x42, 0x94, 0x70, 0x0a, 0x65, 0x0c, 0x5d, 0x31, 0x6d, 0x14, 0x89, 0x4a, 0x03,
	0x7b, 0x00, 0xc7, 0xeb, 0x8b, 0xf4, 0x4c, 0x49, 0x8d, 0x8c, 0x41, 0x29, 0x8e, 0x85, 0xb7, 0xbc,
	0x83, 0xce, 0xeb, 0xea, 0x42, 0xa6, 0x9a, 0x5d, 0xc0, 0x3e, 0x89, 0x16, 0x1e, 0x75, 0x2d, 0x3b,
	0x95, 0x24, 0xec, 0x7b, 0x76, 0x07, 0xd8, 0x33, 0x9a, 0x41, 0x12, 0x48, 0x5f, 0xad, 0x46, 0xd8,
	0xd1, 0xd8, 0xfe, 0xb6, 0xe0, 0x64, 0x23, 0xf5, 0x0f, 0x11, 0x9b, 0x16, 0x14, 0xfe, 0xb1, 0xa0,
	0x98, 0x6f, 0x41, 0x29, 0x67, 0x88, 0x72, 0x76, 0x08, 0x76, 0x0b, 0x87, 0x94, 0xc1, 0x85, 0xe6,
	0x73, 0x77, 0x2a, 0xbc, 0x46, 0xa5, 0x6d, 0x75, 0x0e, 0x9c, 0x3a, 0xa1, 0x7d, 0xfd, 0x9e, 0x60,
	0x0f, 0x5f, 0x16, 0xd4, 0x12, 0xf5, 0x6f, 0x18, 0xcd, 0xc5, 0x18, 0xd9, 0x0b, 0xd4, 0xa3, 0xa5,
	0xa3, 0xdc, 0x9d, 0x09, 0x76, 0xd9, 0xcd, 0x6c, 0x7a, 0x6b, 0xa9, 0xcd, 0xab, 0xdd, 0x64, 0xea,
	0x81, 0xbd, 0xc7, 0x86, 0x70, 0x16, 0xa0, 0xe1, 0xa9, 0x3e, 0xe9, 0x2b, 0x3e, 0x5a, 0x70, 0xb2,
	0xe2, 0x26, 0x5b, 0xf8, 0xdb, 0xea, 0x66, 0x2b, 0x97, 0x5f, 0xf5, 0x7e, 0xba, 0x1f, 0xde, 0x05,
	0xc2, 0x4c, 0xe2, 0x51, 0x77, 0xac, 0xc2, 0xde, 0x87, 0x9a, 0x48, 0xb9, 0xe0, 0x93, 0x58, 0x06,
	0xbd, 0xed, 0x07, 0x3a, 0xaa, 0xd0, 0xef, 0xf1, 0x27, 0x00, 0x00, 0xff, 0xff, 0xf4, 0x04, 0xc8,
	0x27, 0xbb, 0x02, 0x00, 0x00,
}
